name: remont_estimate
description: Budget & Material Tracker for Home Renovation.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  excel: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^11.0.0
  gal: ^2.3.2
  image_picker: ^1.2.2
  open_file: ^3.5.11
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  pdf: ^3.12.0
  share_plus: ^13.1.0
  uuid: ^4.5.3
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  firebase_storage: ^13.4.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#EDF1EE"
  adaptive_icon_foreground: assets/icon/app_icon.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/fonts/
